project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*/solution/"
    - "!*/student/"

website:
  page-navigation: true
  title: "R is Your Friend"
  description: "Index of Course Materials"
  site-url: "https://R-is-your-friend.github.io/course-assessments"
  repo-url: https://github.com/R-is-your-friend/course-assessments
  repo-actions: [issue]

  page-footer:
    right: "This page is built with ❤️️ and [Quarto](https://quarto.org/)."
    left: "Built by Kelly Bodwin, Charlotte Mann,  Zoe Rehnberg, Emily Robinson, Julia Schedler, and Allison Theobold."
    background: "#7fcdbb"

  navbar:
    pinned: true
    background: "#7fcdbb"
    right:
      - href: index.qmd
        text: Schedule
      - href: data/data-index.qmd
        text: Data


format:
  html:
    code-link: true
    theme:
      light: [cosmo, style/customcallouts.scss, style/risfriend.scss]
      dark: [cosmo, style/customcallouts.scss, style/risfriend.scss]
    code-copy: true
    mainfont: "Atkinson Hyperlegible"
    code-overflow: wrap
    toc: true
    linkcolor: "#8856a7"
    code-annotations: below
    toc-depth: 4
  # pdf:
  #   documentclass: scrreprt

filters:
  - style/custom_callout.lua
  
editor: source

execute: 
  echo: true
  warning: false
  error: true
  freeze: auto
