---
title: "R is Your Friend Course Materials"
tbl-colwidths: [5,5,45,10,10,10,10,10]
---

### Schedule

{{< fa calendar title="An calendar" >}}  This page contains an easy reference the topics, content, and assignments for a semester.

<!--
To update the calendar, add the relative path to the material's .qmd file
-->

```{r}
#| label: packages
#| echo: false
#| message: false
#| warning: false

library(gt)
library(tidyverse)
```


```{r}
#| label: read-data
#| echo: false

d <- readxl::read_excel("index.xlsx")

```


```{r}
#| label: format-calendar-entries
#| echo: false

t <- d |>
  gt() |> 
  text_transform(cells_body(columns = c(preparation)),
                 fn = function(x){
                   ifelse(is.na(x), fontawesome::fa('book', fill_opacity = 0.1), 
                          glue::glue('<a href="{x}"><i class="fa fa-book" style="color: purple;"></i></a>'))
                 }) |> 
  text_transform(cells_body(columns = c(slides)),
                 fn = function(x){
                   ifelse(is.na(x), fontawesome::fa('laptop', fill_opacity = 0.1), 
                           glue::glue('<a href="{x}"><i class="fa fa-laptop" style="color: purple;"></i></a>'))
                 }) |> 
  text_transform(cells_body(columns = c(activity)),
                 fn = function(x){
                   ifelse(is.na(x), fontawesome::fa('users', fill_opacity = 0.1),
                          glue::glue('<a href="{x}"><i class="fa fa-users" style="color: purple;"></i></a>'))
                  }) |> 
  text_transform(cells_body(columns = c(lab)),
                 fn = function(x){
                   ifelse(is.na(x), fontawesome::fa('pencil', fill_opacity = 0.1), 
                          glue::glue('<a href="{x}"><i class="fa fa-pencil" style="color: purple;"></i></a>'))
                 }) |> 
  text_transform(cells_body(columns = c(handout)),
                 fn = function(x){
                   ifelse(is.na(x), fontawesome::fa('clipboard', fill_opacity = 0.1), 
                          glue::glue('<a href="{x}"><i class="fa fa-clipboard" style="color: purple;"></i></a>'))
                 }) |> 
  sub_missing(columns = topic, missing_text = "") |> 
  cols_align(align = "center",
             columns = !topic) |> 
  cols_width(
    week:day ~ pct(3),
    topic ~ pct(15),
    preparation:lab ~ pct(6)
  )

t <- t |>
  as_raw_html() 
```

```{r}
#| echo: false
#| results: "asis"
#| label: output-calendar

cat(t)
```


