{
  "hash": "eed2934ef839218d34615329235932dc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"PA 12: Find the mystery animal\"\nfilters:\n  - versions\nversions:\n  - student:\n      out-dir: \"..\"\n      yaml:\n        author: \"Your Name\"\n        embed-resources: true\n  - instructions:\n      out-dir: \"..\"\n      yaml:\n        eval: false\n  - solution:\n      out-dir: \"..\"\n      out-file: \"pa12-solution.qmd\"\n      yaml:\n        author: \"SOLUTIONS\"\n        embed-resources: true\nformat: \n  html:\n    code-tools: true\n    toc: true      \nexecute: \n  error: true\n  echo: true\n  message: false\n  warning: false\n---\n\nA group of scientists is studying the diet of a particular mystery animal. They\nhave performed an experiment: First, they recorded the weights of each individual\nanimal in their sample.  Then, they fed the animals only roasted duck for one\nyear, after which they recorded the new weights of the animals.\n\nThe dataset below contains the weights *before* and *after* a year \nof the roasted duck diet.\n\n:::{.version-instructions}\n[Download starter .qmd file](../student/pa12-regression.qmd)\n\n[Download data -- `12-mystery_animal.csv`](../../data/12-mystery_animal.csv)\n:::\n\n\n::: {.cell versions='solution'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ndat <- read_csv(here::here(\"data\", \"12-mystery_animal.csv\"))\n```\n:::\n\n\n## Data Exploration\n\n1. Make a scatter plot of this data, with the `weight_before` measurements on the x-axis \nand the `weight_after` measurements on the y-axis.  \n\n2. What appears to be the slope? Why does this make sense in the context of this data?\n\n::: {.versions-solution}\n\nBoth smaller and bigger animals might gain some weight, but the overall weights\ndon't change much - we expect `weight_after` to be very similar to `weight_before`.\n\n:::\n\n3. Why is it difficult to estimate the intercept from this data?\n\n::: {.versions-solution}\n\nThe data starts at around 100, since the animals weigh between 100 and 400 pounds.\nSo, we can't see what value the y-axis would have at x = 0.\n\n:::\n\n## Model calculation\n\n1. Write a function called `linear_model` that takes an `x` and `y` vectors as\ninput, and returns the calculated slope and intercept.\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\nlinear_model <- function(x, y) {\n  \n  slope <- cor(x, y)*sd(y)/sd(x)\n  \n  int <- mean(y) - slope*mean(x)\n  \n  return(list(slope = slope, intercept = int))\n  \n}\n```\n:::\n\n\n\n\n2. Use your new function to *fit* a linear model to this data, predicting the\n`after` weights from the `before` weights.\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\nmod <- linear_model(x = dat$weight_before, y = dat$weight_after)\nmod\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$slope\n[1] 1.192037\n\n$intercept\n[1] 2.854212\n```\n\n\n:::\n:::\n\n\n\n2. What is the *slope* of this model?  Does that match what you predicted? Why\ndo you think it's not *exactly* equal to 1?\n\n::: {.versions-solution}\n1.19.  Yes, this is close to 1.  But there is always some variability in how\nmuch weight the animals gain, so the relationship is not exact for this particular\ndataset.\n:::\n\n\n3. What is the *intercept* of this model?  What does that suggest to you about\nthe Duck Diet?  Did the animals gain weight, lose weight, or neither?\n\n::: {.versions-solution}\n\n2.85.  This means they gained a little weight; about 3 pounds on average.\n\n:::\n\n## Predictions and residuals\n\n4. Add a column to the dataset named `pred_after`, which contains the *predicted*\nweight of the animals after a year of duck diet, based on this model.\n\n\n::: {.cell versions='solution'}\n\n```{.r .cell-code}\ndat <- dat |>\n  mutate(\n    pred_after = 1.19*weight_before + 2.85\n  )\n```\n:::\n\n\n\n\n5. Add a column to the dataset named `residual`, equal to the *predicted* value\nsubtracted from each *actual observed* value.\n\n\n\n::: {.cell versions='solution'}\n\n```{.r .cell-code}\ndat <- dat |>\n  mutate(\n    resid = weight_after - pred_after\n  )\n```\n:::\n\n \n\n6. Make a scatterplot with the residuals on the y-axis and the predicted values\non the x-axis.  \n\n\n::: {.cell versions='solution'}\n\n```{.r .cell-code}\ndat |>\n  ggplot() +\n  aes(x = pred_after, y = resid) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](pa12-regression_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\n7. What is the mystery animal that was fed the roasted duck diet?\n\n::: {.versions-solution}\n\nA Shark!\n\n:::\n",
    "supporting": [
      "pa12-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}