---
title: "Week 4: Data is Friend"
number-sections: true
number-depth: 2
---

```{r}
#| include: false
#| label: packages-setup

library(tidyverse)
```


::: columns
::: {.column width="48%"}
#### 📖 Readings: 60 min

#### 🏋🏾‍♂️ Activities: 0 min

:::

::: {.column width="4%"}
:::

::: {.column width="48%"}
#### 📽 Videos: 0 min 

#### 💻 Tutorials: 0 min
:::
:::

------------------------------------------------------------------------


::: callout
## Learning Objectives

+ Define the observational unit (rows) and variables (columns) of rectangular data
+ Identify variable types given rectangular data
+ Explore rectangular data quickly in R (with code and with RStudio visually)
+ Read rectangular data with various delimiters into R using an appropriate `readr` or `readxl` function
+ Define relative versus absolute file paths
+ Integrate R code and Markdown text in **Quarto** documents
:::

## Rectangular Data

### 📖 Required Reading: [Rectangular Data](https://r-is-your-friend.github.io/course-pack/04-data-is-friend.html#rectangular-data)

By the end of the reading, you should be able to answer the following questions:

::: {.callout-check-in}

TO-DO

:::

## Importing Data into R

### 📖 Required Reading: [File Paths](https://r-is-your-friend.github.io/course-pack/04-data-is-friend.html#file-paths)
### 📖 Required Reading: [R4DS 7.1-7.3](https://r4ds.hadley.nz/data-import.html) about reading in data files
### 📖 Required Reading: [R4DS 7.5](https://r4ds.hadley.nz/data-import.html#sec-writing-to-a-file) about saving data externally
### 📖 Required Reading: [R4DS 20](https://r4ds.hadley.nz/spreadsheets.html) about working with Excel files

By the end of the reading, you should be able to answer the following questions:

::: {.callout-check-in}

TO-DO

+ Show code for reading in the data -- read_table()? read_csv()? read_xlsx()? read_delim(delim = _____)? 
  + What if the data looks like xxxx.
+ How many dimensions is the data? -- use dim()
+ Screenshot of reflected file folder structure & Files tab in R.
+ match the View(), str(), glimpse()
  + what sort of variable is each? ID = 1, 2, 3, 4, is read in as numeric. Does that make sense What is this 1L (integers). What in the world is a double?
:::

## Quarto

### 📖 Required Reading: [R4DS 28](https://r4ds.hadley.nz/quarto.html) about Quarto

By the end of the reading, you should be able to answer the following questions:

::: {.callout-check-in}

TO-DO

:::

