---
title: "Week 9: Special Variable Types"
number-sections: true
number-depth: 2
---

```{r}
#| include: false
#| label: packages-setup

library(tidyverse)
```


::: columns
::: {.column width="48%"}
#### 📖 Readings: 60 min

#### 🏋🏾‍♂️ Activities: 0 min

:::

::: {.column width="4%"}
:::

::: {.column width="48%"}
#### 📽 Videos: 0 min 

#### 💻 Tutorials: 0 min
:::
:::

------------------------------------------------------------------------




## Character Variables and Strings

::: callout
## Learning Objectives

+ Clean and extract information from character variables using stringr
+ Recognize what a basic regular expression will match

:::

### 📖 Required Reading: [R4DS 14.1-14.5: Strings](https://r4ds.had.co.nz/strings.html#strings)

### 📖 Required Reading: [R4DS 15.1-15.4: Strings](https://r4ds.hadley.nz/regexps.html)


By the end of the reading, you should be able to answer the following questions:

::: {.callout-check-in}

TO-DO

:::

## Date and Time Variables

::: callout
## Learning Objectives
+ Work with date and time variables using lubridate
+ Convert a string variable into a date / time variable 
+ Extract date / time information from a date / time variable (e.g. month, year, day of the week, etc) 
+ Convert between time zones
:::


### 📖 Required Reading: [R4DS 17: Dates and Times](https://r4ds.hadley.nz/datetimes.html)

#### 📽 Optional Video: [Working wtih Dates](https://www.youtube.com/watch?v=SEPjN2AJqbo)

By the end of the reading, you should be able to answer the following questions:

::: {.callout-check-in}

TO-DO

:::

