---
title: "Data Referenced in Materials"
---






Week 4:

- [magic-csv.csv](04-magic-csv.csv) (created by us!)

Week 5:

- `penguins`([palmerpenguins](https://allisonhorst.github.io/palmerpenguins/) package)
- `txhousing` ([ggplot2](https://ggplot2.tidyverse.org/reference/txhousing.html) package)


Week 6

- `cereal` ([liver](https://cran.r-project.org/web/packages/liver/refman/liver.html#cereal) package)
- colleges.csv (where the heck is this data from y'all????? there is just a dropbox link to it)
- [teacher_evals.csv](06-teacher-evals.csv)  ([source](https://www.openicpsr.org/openicpsr/project/149801/version/V1/view)) ([documentation](https://earobinson95.github.io/stat331-calpoly/lab-assignments/Lab3-dplyr/teacher_evals_codebook.pdf))

Week 7

- more `cereal` :) 
- [SIPRI-Milex-data-1949-2024.xlsx](07-SIPRI-Milex-data-1949-2024.xlsx) ([source](https://www.sipri.org/databases/milex)) (downloaded 1/3/25)

Week 8


- [TS_data.xlsx](08-TS_data.xlsx) (created by Dr. Rehnberg?)
- [cities.csv]() ([source]())
- [links.csv]() ([source]())
- [dists.csv](08-dists.csv) (calculated from cities.csv and links.csv. [script](_source/08-twin_dist/prepare-data.qmd))
- [childcare_costs.csv](https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-05-09/childcare_costs.csv) ([source](https://github.com/rfordatascience/tidytuesday/blob/main/data/2023/2023-05-09/readme.md))
- [counties.csv](https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-05-09/counties.csv) ([source](https://github.com/rfordatascience/tidytuesday/blob/main/data/2023/2023-05-09/readme.md))
- [ca_tax_revenue.csv](08-ca_tax_revenue.csv) (compiled from the [California State Controller](https://counties.bythenumbers.sco.ca.gov/#!/year/default). [script](_source/08-ca_tax_revenue/prepare-data.qmd))

Week 9

- [bCH_murder_data.Rdata](09-bCH_murder_data.Rdata) (compiled from the [knight lab](https://mystery.knightlab.com/) at Northwestern University)