---
title: "Lab 2: R is Friend"
format: 
  html:
    toc: true      

author: Instructions
echo: true
eval: true
---
<!-- We need to decide what our AI policy is! -->

::: {.callout-tip collapse="true"}
## Seeking Help

Part of learning to program is learning from a variety of resources. Thus, I expect you will use resources that you find on the internet. There is, however, an important balance between copying someone else's code and *using their code to learn*. Therefore, if you use external resources, I want to know about it. You can "inform" me of any resources you used by **pasting the link to the resource in a code comment next to where you used that resource**.

Additionally, you are permitted and encouraged to work with your peers as you complete lab assignments, but **you are expected to do your own work**. Copying from each other is cheating, and letting people copy from you is also cheating. Please don't do either of those things.
:::

## Create an R Script

Last week, you downloaded a template R script, but you've learned how to make
one of these from scratch. So, this week you are going to make your own R script
for Lab 2!

1. Create a new R script, give it a descriptive and appropriate file name, and
save it in your Week 2 subfolder (of your STAT 1810 folder). 

2. In the newly created R script, add a comment to the top that describes the
contents of this document. *Hint: it's the code for Lab 2!*

## Pismo Beach Water Temperature

It's Saturday, you have some free time, and you're trying to decide if it's warm
enough to go swimming at Pismo Beach! You look up the water temperature at Pismo
Pier on a surf watch website, but the temperature is only listed in degrees
Celsius! What does that even mean???

3. Create a new object to hold to current water temperature in degrees
Celsius -- it's listed as 11 degrees. Make sure you use a **descriptive** 
name for the object!

4. Write one line of code to turn degrees Celsius into degrees Fahrenheit,
incorporating the variable you create in #3. What is the water temperature?

::: {.callout-tip}
Find the appropriate formula on Google for converting Celsius into degrees
Fahrenheit. Pay attention to the order of operations! Parentheses are your
friend!
:::

Since it was too cold to swim on Saturday, you decided to keep track of the
water temperature to see what days might have temperatures warm enough for 
swimming. You observed the following temperatures:

- Sunday: 12°C
- Monday: 13°C
- Tuesday: 16°C
- Wednesday: 14°C
- Thursday: 17°C
- Friday: 16°C
- Saturday: 18°C

5. Create an object to store these seven temperatures.  Make sure you use a
**descriptive** name for the object!

::: {.callout-tip}
Remember to use the `c()` function and to separate values with a `,`.
:::

6. Create an object to store the seven days these temperatures are associated 
with.  Make sure you use a **descriptive** name for the object!

7. Now that we have temperatures **and** their associated days of the week, 
let's combine these into **one** object. Create an object that stores *both* the
temperatures you made in #5 **and** the days you made in #6. 

8. Now, let's change the temperature values from Celsius into Fahrenheit. Be
sure to save the updated values back into the original object (like you did 
in the Practice Activity)! *Hint: You should borrow the mathematical steps you used in #4!*

9. If 60 degrees Fahrenheit is your threshold for swimming in the ocean, how
many days had "swimable" temperatures?

## Do Other People Like Your Favorite Movies?

Let's use [Rotten Tomatoes](https://www.rottentomatoes.com/) to find the average
rating for five of your favorite movies. Do other people like them as much as
you do?

::: {.callout-tip}
When looking up your favorite movies, you can...

* use the critic rating **or** the general audience rating.
* record the rating as a percent **or** a proportion (e.g., 72%  or 0.72).

For both, make a decision and be consistent!
:::

10. Create a variable that contains the Rotten Tomatoes ratings for your five
favorite movies. Make sure you use a **descriptive** variable name.

11. Create a variable that contains the names of your five favorite movies. 
Remember the names should go in the same order as the ratings! Make sure you
use a **descriptive** variable name.

12. Write a line of code to find the maximum rating for your top five movies. 
Write a second line of code to find the minimum rating.

13. Write a line of code to find the average rating for your top five movies.

We've asked some of the statistics faculty what their favorite movie is and
assembled them into a vector. 

14. Use the `%in%` operator to check if any of these movies are included in 
the top five movies you made in #11. Here is an example of how to use the
`%in%` operator:

```{r}
"bananna" %in% c("apple", "kiwi", "banana", "orange")
```

## Reviewing Your Work

15. What variables have you created during this lab? Using a code comment, list
all of the variable names.

::: {.callout-tip}
The Environment pane in the top right corner will show you all the objects 
you've created.
:::

## Make Your Code Readable

16. Add comments throughout your script that describe what your code is doing. 
